name: Update docs folder on release

on:
  release:
    types: [published]

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Copy JSON files to docs/
        run: |
          mkdir -p docs
          cp modl_version_21.json docs/
          cp diff_api_21.json docs/

      - name: Commit and push if changed
        run: |
          git add docs/
          git commit -m "Update docs on release ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}